### ISSUE TITLE
Running multiple times

### ISSUE THREAD

**Issue by mjafartp** [Hexagon/croner#86]
My production env has 2 instances of application running (Running app over PM2 )
Currently, this cron running 2 times in my application how to limit to 1?

**Comment by Hexagon** [comment]
So cron is running according to the schedule, but since you have multiple instances you get multiple executions each time? Could you add a check for `process.env.pm_id`, that only starts croner if pm_id is 0 (first instance) or something like that?

https://stackoverflow.com/questions/44554336/node-app-instance-name-when-running-via-pm2-cluster
